title: Changxin Xiang
logo: /photo.jpg
description: A newcomer and explorer of the research in management and economics of sustainability.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
